apiVersion: v1
kind: ServiceAccount
metadata:
  name: userprofileq
  labels:
    app: userprofileq
    component: rbac
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: userprofileq
  labels:
    app: userprofileq
    component: rbac
rules:
# Basic pod and service discovery
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create"]
# Metrics access
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
# Basic secrets access
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["userprofileq-secrets"]
# Storage access for user uploads
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: userprofileq
  labels:
    app: userprofileq
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: userprofileq
subjects:
- kind: ServiceAccount
  name: userprofileq
  namespace: q-platform 