apiVersion: v1
kind: Service
metadata:
  name: userprofileq
  labels:
    app: userprofileq
    component: service
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8005
    targetPort: 8005
  - name: api
    protocol: TCP
    port: 8006
    targetPort: 8006
  - name: admin
    protocol: TCP
    port: 8009
    targetPort: 8009
  - name: metrics
    protocol: TCP
    port: 9091
    targetPort: 9091
  selector:
    app: userprofileq 