apiVersion: v1
kind: ConfigMap
metadata:
  name: knowledgegraphq-config
  labels:
    app: knowledgegraphq
    component: config
data:
  # Application Configuration
  SERVICE_NAME: "knowledgegraphq"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  METRICS_PORT: "9091"
  
  # Network Configuration
  HOST: "0.0.0.0"
  PORT: "8000"
  API_PORT: "8004"
  ADMIN_PORT: "8005"
  
  # Graph Database Configuration
  GRAPH_DB_TYPE: "janusgraph"
  GRAPH_DB_HOST: "janusgraph"
  GRAPH_DB_PORT: "8182"
  GRAPH_DB_NAME: "knowledge"
  
  # JanusGraph Configuration
  JANUSGRAPH_STORAGE_BACKEND: "cassandra"
  JANUSGRAPH_STORAGE_HOSTNAME: "cassandra-cluster"
  JANUSGRAPH_STORAGE_PORT: "9042"
  JANUSGRAPH_STORAGE_KEYSPACE: "janusgraph"
  
  # Elasticsearch Configuration (for indexing)
  ELASTICSEARCH_HOST: "elasticsearch"
  ELASTICSEARCH_PORT: "9200"
  ELASTICSEARCH_INDEX_NAME: "knowledge_graph"
  
  # Gremlin Configuration
  GREMLIN_REMOTE_DRIVER_HOSTS: "janusgraph"
  GREMLIN_REMOTE_DRIVER_PORT: "8182"
  GREMLIN_REMOTE_DRIVER_SERIALIZER: "gryo"
  GREMLIN_POOL_SIZE: "10"
  
  # Query Configuration
  QUERY_TIMEOUT: "30"
  QUERY_MAX_DEPTH: "10"
  TRAVERSAL_TIMEOUT: "60"
  RESULT_LIMIT: "1000"
  
  # Pulsar Configuration
  PULSAR_SERVICE_URL: "pulsar://pulsar-broker:6650"
  PULSAR_ADMIN_URL: "http://pulsar-admin:8080"
  GRAPH_EVENTS_TOPIC: "persistent://public/default/q.knowledgegraph.events"
  GRAPH_QUERIES_TOPIC: "persistent://public/default/q.knowledgegraph.queries"
  ENTITY_UPDATES_TOPIC: "persistent://public/default/q.knowledgegraph.entity-updates"
  
  # Health Check Configuration
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_PORT: "8000"
  
  # Observability
  ENABLE_TRACING: "true"
  ENABLE_METRICS: "true"
  ENABLE_PROMETHEUS: "true"
  
  # Cache Configuration
  CACHE_ENABLED: "true"
  CACHE_TYPE: "redis"
  CACHE_HOST: "redis"
  CACHE_PORT: "6379"
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "2GB"
  
  # Performance Configuration
  WORKER_PROCESSES: "4"
  WORKER_THREADS: "8"
  REQUEST_QUEUE_SIZE: "1000"
  RESPONSE_TIMEOUT: "300"
  
  # Graph Schema Configuration
  SCHEMA_VALIDATION: "true"
  SCHEMA_EVOLUTION: "true"
  AUTO_SCHEMA_CREATION: "true"
  VERTEX_LABEL_CONSTRAINTS: "true"
  EDGE_LABEL_CONSTRAINTS: "true"
  
  # Entity Management
  ENTITY_DEDUPLICATION: "true"
  ENTITY_LINKING: "true"
  ENTITY_RESOLUTION: "true"
  ENTITY_VALIDATION: "true"
  
  # Relationship Management
  RELATIONSHIP_INFERENCE: "true"
  RELATIONSHIP_WEIGHTING: "true"
  RELATIONSHIP_VALIDATION: "true"
  
  # Graph Analytics
  GRAPH_ANALYTICS_ENABLED: "true"
  CENTRALITY_ALGORITHMS: "pagerank,betweenness,closeness"
  COMMUNITY_DETECTION: "true"
  PATH_FINDING: "true"
  
  # Knowledge Extraction
  KNOWLEDGE_EXTRACTION_ENABLED: "true"
  NER_ENABLED: "true"
  RELATION_EXTRACTION: "true"
  ENTITY_DISAMBIGUATION: "true"
  
  # Integration Configuration
  VECTORSTORE_URL: "http://vectorstore-q:8001"
  QUANTUMPULSE_URL: "http://quantumpulse:8000"
  AGENTQ_URL: "http://agentq-default:8000"
  MANAGER_Q_URL: "http://manager-q:8003"
  
  # Data Import/Export
  IMPORT_ENABLED: "true"
  EXPORT_ENABLED: "true"
  BULK_IMPORT_BATCH_SIZE: "1000"
  EXPORT_FORMATS: "json,rdf,graphml,gexf"
  
  # Backup Configuration
  BACKUP_ENABLED: "true"
  BACKUP_INTERVAL: "3600"
  BACKUP_RETENTION: "7"
  BACKUP_STORAGE: "minio"
  
  # Security Configuration
  AUTHORIZATION_ENABLED: "true"
  VERTEX_LEVEL_SECURITY: "true"
  EDGE_LEVEL_SECURITY: "true"
  AUDIT_LOGGING: "true"
  
  # Monitoring Configuration
  MONITORING_ENABLED: "true"
  MONITORING_INTERVAL: "30"
  ALERT_THRESHOLD_LATENCY: "2000"
  ALERT_THRESHOLD_ERROR_RATE: "0.05"
  
  # Logging Configuration
  LOG_FORMAT: "json"
  LOG_TO_PULSAR: "true"
  LOG_PULSAR_TOPIC: "persistent://public/default/knowledgegraph-logs"
  
  # Environment
  ENVIRONMENT: "production"
  
  # Graph Processing
  GRAPH_PROCESSING_ENABLED: "true"
  STREAMING_PROCESSING: "true"
  BATCH_PROCESSING: "true"
  REAL_TIME_UPDATES: "true"
  
  # ML Integration
  ML_ENABLED: "true"
  GRAPH_EMBEDDINGS: "true"
  LINK_PREDICTION: "true"
  NODE_CLASSIFICATION: "true"
  
  # Visualization
  VISUALIZATION_ENABLED: "true"
  GRAPH_LAYOUT_ALGORITHMS: "force-directed,hierarchical,circular"
  SUBGRAPH_EXTRACTION: "true"
  
  # API Configuration
  API_VERSIONING: "true"
  API_RATE_LIMITING: "true"
  API_DOCUMENTATION: "true"
  GRAPHQL_ENABLED: "true"
  
  # Data Quality
  DATA_QUALITY_CHECKS: "true"
  CONSISTENCY_VALIDATION: "true"
  COMPLETENESS_CHECKS: "true"
  ACCURACY_VALIDATION: "true"
  
  # Scalability Configuration
  HORIZONTAL_SCALING: "true"
  SHARDING_ENABLED: "true"
  REPLICATION_FACTOR: "3"
  LOAD_BALANCING: "round_robin"
  
  # Graph Algorithms
  SHORTEST_PATH: "true"
  MINIMUM_SPANNING_TREE: "true"
  CONNECTED_COMPONENTS: "true"
  CLUSTERING_ALGORITHMS: "true"
  
  # Semantic Web
  RDF_SUPPORT: "true"
  SPARQL_ENDPOINT: "true"
  ONTOLOGY_SUPPORT: "true"
  REASONING_ENGINE: "true"
  
  # Experimental Features
  EXPERIMENTAL_FEATURES_ENABLED: "false"
  BETA_FEATURES_ENABLED: "false" 