apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: knowledgegraphq-pdb
  labels:
    app: knowledgegraphq
    component: availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: knowledgegraphq 