apiVersion: v2
name: q-platform
description: Q Platform - Advanced Multi-Agent AI System for Real-time Inference and Decision-making
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/your-org/q-platform
sources:
  - https://github.com/your-org/q-platform
maintainers:
  - name: Q Platform Team
    email: platform-team@your-org.com
keywords:
  - ai
  - multi-agent
  - real-time
  - distributed
  - quantum
  - inference
  - microservices
  - platform
annotations:
  category: AI/ML Platform
  licenses: Apache-2.0
  images: |
    - name: manager-q
      image: 192.168.67.2:5000/manager-q:1.0.0
    - name: agent-q
      image: 192.168.67.2:5000/agent-q:1.0.0
    - name: h2m-service
      image: 192.168.67.2:5000/h2m-service:1.0.0
    - name: quantum-pulse
      image: 192.168.67.2:5000/quantum-pulse:1.0.0
    - name: vector-store-q
      image: 192.168.67.2:5000/vector-store-q:1.0.0
    - name: knowledge-graph-q
      image: 192.168.67.2:5000/knowledge-graph-q:1.0.0
    - name: integration-hub
      image: 192.168.67.2:5000/integration-hub:1.0.0
    - name: user-profile-q
      image: 192.168.67.2:5000/user-profile-q:1.0.0
    - name: webapp-q
      image: 192.168.67.2:5000/webapp-q:1.0.0

dependencies:
  # Core Infrastructure Dependencies
  - name: pulsar
    version: "3.0.0"
    repository: "https://pulsar.apache.org/charts"
    condition: pulsar.enabled
  - name: cassandra
    version: "9.10.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: cassandra.enabled
  - name: milvus
    version: "4.0.12"
    repository: "https://milvus-io.github.io/milvus-helm/"
    condition: milvus.enabled
  - name: ignite
    version: "1.0.0"
    repository: "https://apache.github.io/ignite-helm"
    condition: ignite.enabled
  - name: elasticsearch
    version: "8.11.0"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
  - name: minio
    version: "5.0.14"
    repository: "https://charts.min.io/"
    condition: minio.enabled
  - name: flink
    version: "1.6.1"
    repository: "https://archive.apache.org/dist/flink/flink-1.17.0/"
    condition: flink.enabled
  - name: seatunnel
    version: "2.3.3"
    repository: "https://seatunnel.apache.org/charts"
    condition: seatunnel.enabled
  
  # Security & Identity
  - name: keycloak
    version: "18.2.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: keycloak.enabled
  - name: vault
    version: "0.27.0"
    repository: "https://helm.releases.hashicorp.com"
    condition: vault.enabled
  - name: external-secrets
    version: "0.9.11"
    repository: "https://charts.external-secrets.io"
    condition: external-secrets.enabled
  
  # Observability
  - name: prometheus
    version: "25.4.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.3.5"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: jaeger
    version: "0.71.14"
    repository: "https://jaegertracing.github.io/helm-charts"
    condition: jaeger.enabled
  - name: tempo
    version: "1.7.2"
    repository: "https://grafana.github.io/helm-charts"
    condition: tempo.enabled
  
  # Service Mesh & Networking
  - name: istio-base
    version: "1.20.1"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: istio.enabled
  - name: istiod
    version: "1.20.1"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: istio.enabled
  - name: istio-gateway
    version: "1.20.1"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: istio.enabled
  
  # GitOps & CI/CD
  - name: argo-cd
    version: "5.51.5"
    repository: "https://argoproj.github.io/argo-helm"
    condition: argocd.enabled
  - name: harbor
    version: "1.13.2"
    repository: "https://helm.goharbor.io"
    condition: harbor.enabled 