apiVersion: v1
kind: ConfigMap
metadata:
  name: integrationhub-config
  labels:
    app: integrationhub
    component: config
data:
  # Application Configuration
  SERVICE_NAME: "integrationhub"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  METRICS_PORT: "9091"
  
  # Network Configuration
  HOST: "0.0.0.0"
  PORT: "8006"
  API_PORT: "8007"
  ADMIN_PORT: "8010"
  
  # Integration Configuration
  INTEGRATION_TYPES: "api,webhook,database,queue,file,auth"
  MAX_CONNECTIONS: "1000"
  CONNECTION_TIMEOUT: "30"
  REQUEST_TIMEOUT: "60"
  
  # Pulsar Configuration
  PULSAR_SERVICE_URL: "pulsar://pulsar-broker:6650"
  PULSAR_ADMIN_URL: "http://pulsar-admin:8080"
  INTEGRATION_EVENTS_TOPIC: "persistent://public/default/q.integrationhub.events"
  INTEGRATION_REQUESTS_TOPIC: "persistent://public/default/q.integrationhub.requests"
  INTEGRATION_RESPONSES_TOPIC: "persistent://public/default/q.integrationhub.responses"
  
  # Health Check Configuration
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_PORT: "8006"
  
  # Observability
  ENABLE_TRACING: "true"
  ENABLE_METRICS: "true"
  ENABLE_PROMETHEUS: "true"
  
  # Cache Configuration
  CACHE_ENABLED: "true"
  CACHE_TYPE: "redis"
  CACHE_HOST: "redis"
  CACHE_PORT: "6379"
  CACHE_TTL: "1800"
  CACHE_MAX_SIZE: "500MB"
  
  # Performance Configuration
  WORKER_PROCESSES: "4"
  WORKER_THREADS: "8"
  REQUEST_QUEUE_SIZE: "2000"
  RESPONSE_TIMEOUT: "300"
  
  # API Integration Configuration
  API_RATE_LIMITING: "true"
  API_RETRY_COUNT: "3"
  API_RETRY_DELAY: "1.0"
  API_CIRCUIT_BREAKER: "true"
  API_CIRCUIT_BREAKER_THRESHOLD: "5"
  
  # Webhook Configuration
  WEBHOOK_ENABLED: "true"
  WEBHOOK_VERIFICATION: "true"
  WEBHOOK_TIMEOUT: "30"
  WEBHOOK_RETRY_COUNT: "3"
  WEBHOOK_QUEUE_SIZE: "1000"
  
  # Database Integration
  DATABASE_INTEGRATION_ENABLED: "true"
  DB_CONNECTION_POOL_SIZE: "20"
  DB_CONNECTION_TIMEOUT: "30"
  DB_QUERY_TIMEOUT: "60"
  
  # File Integration
  FILE_INTEGRATION_ENABLED: "true"
  FILE_UPLOAD_MAX_SIZE: "500MB"
  FILE_DOWNLOAD_TIMEOUT: "300"
  FILE_STORAGE: "minio"
  
  # Authentication Integration
  AUTH_INTEGRATION_ENABLED: "true"
  OAUTH2_ENABLED: "true"
  SAML_ENABLED: "true"
  LDAP_ENABLED: "true"
  API_KEY_ENABLED: "true"
  
  # Message Queue Integration
  QUEUE_INTEGRATION_ENABLED: "true"
  QUEUE_TYPES: "pulsar,kafka,rabbitmq,sqs"
  QUEUE_BATCH_SIZE: "100"
  QUEUE_TIMEOUT: "30"
  
  # Security Configuration
  ENCRYPTION_ENABLED: "true"
  TLS_ENABLED: "true"
  CREDENTIAL_ENCRYPTION: "true"
  SECRET_ROTATION: "true"
  
  # Monitoring Configuration
  MONITORING_ENABLED: "true"
  MONITORING_INTERVAL: "30"
  ALERT_THRESHOLD_LATENCY: "5000"
  ALERT_THRESHOLD_ERROR_RATE: "0.10"
  
  # Integration Specific Services
  SLACK_INTEGRATION: "true"
  TEAMS_INTEGRATION: "true"
  EMAIL_INTEGRATION: "true"
  SMS_INTEGRATION: "true"
  GITHUB_INTEGRATION: "true"
  GITLAB_INTEGRATION: "true"
  JIRA_INTEGRATION: "true"
  CONFLUENCE_INTEGRATION: "true"
  
  # Cloud Provider Integrations
  AWS_INTEGRATION: "true"
  AZURE_INTEGRATION: "true"
  GCP_INTEGRATION: "true"
  
  # Database Integrations
  POSTGRESQL_INTEGRATION: "true"
  MYSQL_INTEGRATION: "true"
  MONGODB_INTEGRATION: "true"
  CASSANDRA_INTEGRATION: "true"
  ELASTICSEARCH_INTEGRATION: "true"
  
  # Data Format Support
  SUPPORTED_FORMATS: "json,xml,csv,avro,parquet,protobuf"
  DATA_TRANSFORMATION: "true"
  SCHEMA_VALIDATION: "true"
  
  # Backup Configuration
  BACKUP_ENABLED: "true"
  BACKUP_INTERVAL: "3600"
  BACKUP_RETENTION: "7"
  BACKUP_STORAGE: "minio"
  
  # Logging Configuration
  LOG_FORMAT: "json"
  LOG_TO_PULSAR: "true"
  LOG_PULSAR_TOPIC: "persistent://public/default/integrationhub-logs"
  
  # Environment
  ENVIRONMENT: "production"
  
  # Connector Management
  CONNECTOR_REGISTRY: "true"
  CONNECTOR_VERSIONING: "true"
  CONNECTOR_DISCOVERY: "true"
  CONNECTOR_HEALTH_CHECK: "true"
  
  # Data Pipeline Configuration
  PIPELINE_ENABLED: "true"
  PIPELINE_PARALLEL_EXECUTION: "true"
  PIPELINE_ERROR_HANDLING: "true"
  PIPELINE_RETRY_LOGIC: "true"
  
  # Integration with Q Platform Services
  MANAGER_Q_URL: "http://manager-q:8003"
  AGENT_Q_URL: "http://agentq-default:8000"
  VECTOR_STORE_URL: "http://vectorstore-q:8001"
  KNOWLEDGE_GRAPH_URL: "http://knowledgegraphq:8000"
  QUANTUM_PULSE_URL: "http://quantumpulse:8000"
  H2M_URL: "http://h2m:8008"
  
  # Workflow Integration
  WORKFLOW_INTEGRATION: "true"
  WORKFLOW_TRIGGERS: "true"
  WORKFLOW_ACTIONS: "true"
  WORKFLOW_VALIDATION: "true"
  
  # Real-time Integration
  REALTIME_SYNC: "true"
  STREAMING_ENABLED: "true"
  EVENT_SOURCING: "true"
  CHANGE_DATA_CAPTURE: "true"
  
  # Batch Integration
  BATCH_PROCESSING: "true"
  BATCH_SCHEDULING: "true"
  BATCH_SIZE: "1000"
  BATCH_TIMEOUT: "300"
  
  # API Gateway Integration
  API_GATEWAY_ENABLED: "true"
  API_RATE_LIMITING_GLOBAL: "true"
  API_AUTHENTICATION: "true"
  API_AUTHORIZATION: "true"
  
  # Protocol Support
  HTTP_ENABLED: "true"
  HTTPS_ENABLED: "true"
  WEBSOCKET_ENABLED: "true"
  GRPC_ENABLED: "true"
  GRAPHQL_ENABLED: "true"
  REST_ENABLED: "true"
  SOAP_ENABLED: "true"
  
  # Configuration Management
  CONFIG_VERSIONING: "true"
  CONFIG_VALIDATION: "true"
  CONFIG_ENCRYPTION: "true"
  CONFIG_BACKUP: "true"
  
  # Testing Configuration
  INTEGRATION_TESTING: "true"
  MOCK_SERVICES: "true"
  SANDBOX_MODE: "true"
  
  # Compliance Configuration
  GDPR_COMPLIANCE: "true"
  HIPAA_COMPLIANCE: "true"
  SOX_COMPLIANCE: "true"
  AUDIT_LOGGING: "true"
  
  # Experimental Features
  EXPERIMENTAL_FEATURES_ENABLED: "false"
  BETA_FEATURES_ENABLED: "false" 