apiVersion: v1
kind: ConfigMap
metadata:
  name: quantumpulse-config
  labels:
    app: quantumpulse
    component: config
data:
  # Application Configuration
  SERVICE_NAME: "quantumpulse"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  METRICS_PORT: "9091"
  
  # Network Configuration
  HOST: "0.0.0.0"
  PORT: "8000"
  API_PORT: "8001"
  ADMIN_PORT: "8002"
  
  # LLM Configuration
  DEFAULT_MODEL: "gpt-4"
  FALLBACK_MODEL: "gpt-3.5-turbo"
  MAX_TOKENS: "4096"
  TEMPERATURE: "0.7"
  TOP_P: "0.9"
  FREQUENCY_PENALTY: "0.0"
  PRESENCE_PENALTY: "0.0"
  
  # Model Management
  MODEL_CACHE_SIZE: "10"
  MODEL_CACHE_TTL: "3600"
  MODEL_WARMUP_ENABLED: "true"
  MODEL_HEALTH_CHECK_INTERVAL: "60"
  
  # Inference Configuration
  INFERENCE_TIMEOUT: "120"
  INFERENCE_RETRY_COUNT: "3"
  INFERENCE_RETRY_DELAY: "1.0"
  BATCH_SIZE: "8"
  PARALLEL_REQUESTS: "16"
  
  # Quantum Enhancement Configuration
  QUANTUM_ENABLED: "true"
  QUANTUM_BACKEND: "simulator"
  QUANTUM_CIRCUITS: "optimization,search,pattern-recognition"
  QUANTUM_OPTIMIZATION_ENABLED: "true"
  
  # Pulsar Configuration
  PULSAR_SERVICE_URL: "pulsar://pulsar-broker:6650"
  PULSAR_ADMIN_URL: "http://pulsar-admin:8080"
  INFERENCE_REQUESTS_TOPIC: "persistent://public/default/q.quantumpulse.requests"
  INFERENCE_RESPONSES_TOPIC: "persistent://public/default/q.quantumpulse.responses"
  MODEL_EVENTS_TOPIC: "persistent://public/default/q.quantumpulse.model-events"
  
  # Health Check Configuration
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_PORT: "8000"
  
  # Observability
  ENABLE_TRACING: "true"
  ENABLE_METRICS: "true"
  ENABLE_PROMETHEUS: "true"
  
  # Cache Configuration
  CACHE_ENABLED: "true"
  CACHE_TYPE: "redis"
  CACHE_HOST: "redis"
  CACHE_PORT: "6379"
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "1GB"
  
  # Vector Store Configuration
  VECTOR_STORE_ENABLED: "true"
  VECTOR_STORE_URL: "http://vectorstore-q:8001"
  EMBEDDING_MODEL: "text-embedding-ada-002"
  EMBEDDING_DIMENSION: "1536"
  
  # Performance Configuration
  WORKER_PROCESSES: "4"
  WORKER_THREADS: "8"
  REQUEST_QUEUE_SIZE: "1000"
  RESPONSE_TIMEOUT: "300"
  
  # Security Configuration
  API_KEY_REQUIRED: "true"
  RATE_LIMITING_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "60"
  
  # Load Balancing
  LOAD_BALANCER_TYPE: "round_robin"
  HEALTH_CHECK_ENABLED: "true"
  CIRCUIT_BREAKER_ENABLED: "true"
  CIRCUIT_BREAKER_THRESHOLD: "5"
  CIRCUIT_BREAKER_TIMEOUT: "60"
  
  # Model Specific Configuration
  OPENAI_API_VERSION: "2023-12-01-preview"
  ANTHROPIC_API_VERSION: "2023-06-01"
  GOOGLE_API_VERSION: "v1"
  
  # Fine-tuning Configuration
  FINE_TUNING_ENABLED: "true"
  FINE_TUNING_STORAGE: "minio"
  FINE_TUNING_BUCKET: "quantumpulse-models"
  
  # Logging Configuration
  LOG_FORMAT: "json"
  LOG_TO_PULSAR: "true"
  LOG_PULSAR_TOPIC: "persistent://public/default/quantumpulse-logs"
  
  # Environment
  ENVIRONMENT: "production"
  
  # Monitoring Configuration
  MONITORING_ENABLED: "true"
  MONITORING_INTERVAL: "30"
  ALERT_THRESHOLD_LATENCY: "5000"
  ALERT_THRESHOLD_ERROR_RATE: "0.05"
  
  # Model Registry Configuration
  MODEL_REGISTRY_ENABLED: "true"
  MODEL_REGISTRY_URL: "http://model-registry:8080"
  MODEL_VERSIONING_ENABLED: "true"
  
  # Distributed Inference
  DISTRIBUTED_INFERENCE_ENABLED: "true"
  NODE_DISCOVERY_ENABLED: "true"
  NODE_HEARTBEAT_INTERVAL: "10"
  
  # Data Processing
  PREPROCESSING_ENABLED: "true"
  POSTPROCESSING_ENABLED: "true"
  TEXT_SANITIZATION: "true"
  
  # Integration Configuration
  MANAGER_Q_URL: "http://manager-q:8003"
  AGENT_Q_URL: "http://agentq-default:8000"
  H2M_URL: "http://h2m:8008"
  
  # Backup Configuration
  BACKUP_ENABLED: "true"
  BACKUP_INTERVAL: "3600"
  BACKUP_RETENTION: "7"
  
  # GPU Configuration
  GPU_ENABLED: "false"
  GPU_MEMORY_FRACTION: "0.8"
  CUDA_VISIBLE_DEVICES: ""
  
  # Experimental Features
  EXPERIMENTAL_FEATURES_ENABLED: "false"
  BETA_MODELS_ENABLED: "false" 