apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: quantumpulse-pdb
  labels:
    app: quantumpulse
    component: availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: quantumpulse 