apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-q-config
  labels:
    app: manager-q
    component: config
data:
  # Application Configuration
  SERVICE_NAME: "manager-q"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  METRICS_PORT: "9091"
  
  # Network Configuration
  HOST: "0.0.0.0"
  PORT: "8003"
  
  # Pulsar Configuration
  PULSAR_SERVICE_URL: "pulsar://pulsar-broker:6650"
  PULSAR_ADMIN_URL: "http://pulsar-admin:8080"
  
  # Health Check Configuration
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_PORT: "8003"
  
  # Workflow Configuration
  MAX_CONCURRENT_WORKFLOWS: "100"
  MAX_CONCURRENT_TASKS: "500"
  WORKFLOW_TIMEOUT_HOURS: "24"
  
  # Resource Management
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: "5"
  CIRCUIT_BREAKER_RECOVERY_TIMEOUT: "60"
  
  # Observability
  ENABLE_TRACING: "true"
  ENABLE_METRICS: "true"
  ENABLE_PROMETHEUS: "true"
  
  # Database Configuration
  IGNITE_ENABLED: "true"
  IGNITE_HOST: "ignite-cluster"
  IGNITE_PORT: "10800"
  
  # Vector Store Configuration
  VECTORSTORE_URL: "http://vectorstore-q:8001"
  
  # Knowledge Graph Configuration
  KNOWLEDGEGRAPH_URL: "http://knowledgegraphq:8000"
  
  # Quantum Pulse Configuration
  QUANTUMPULSE_URL: "http://quantumpulse-api:8000"
  
  # Environment
  ENVIRONMENT: "production"
  
  # Retry Configuration
  MAX_RETRIES: "3"
  RETRY_DELAY: "1.0"
  
  # Security Configuration
  ENABLE_CORS: "true"
  ALLOWED_ORIGINS: "*"
  
  # Performance Configuration
  WORKER_THREADS: "4"
  REQUEST_TIMEOUT: "30"
  
  # Logging Configuration
  LOG_FORMAT: "json"
  LOG_TO_PULSAR: "true"
  LOG_PULSAR_TOPIC: "persistent://public/default/manager-q-logs" 