apiVersion: v1
kind: Secret
metadata:
  name: manager-q-secrets
  labels:
    app: manager-q
    component: secrets
type: Opaque
data:
  # Vault Configuration (base64 encoded)
  VAULT_TOKEN: ""  # To be populated by external secret operator or vault injection
  VAULT_ADDR: ""   # To be populated by external secret operator or vault injection
  
  # API Keys (base64 encoded)
  API_SECRET_KEY: ""  # To be populated by external secret operator
  
  # Database Credentials (base64 encoded)
  IGNITE_USERNAME: ""  # To be populated by external secret operator
  IGNITE_PASSWORD: ""  # To be populated by external secret operator
  
  # Pulsar Authentication (base64 encoded)
  PULSAR_AUTH_TOKEN: ""  # To be populated by external secret operator
  PULSAR_TLS_CERT: ""    # To be populated by external secret operator
  PULSAR_TLS_KEY: ""     # To be populated by external secret operator
  
  # Service Authentication (base64 encoded)
  SERVICE_AUTH_TOKEN: ""     # To be populated by external secret operator
  VECTORSTORE_AUTH_TOKEN: "" # To be populated by external secret operator
  KNOWLEDGEGRAPH_AUTH_TOKEN: "" # To be populated by external secret operator
  QUANTUMPULSE_AUTH_TOKEN: ""   # To be populated by external secret operator
  
  # Encryption Keys (base64 encoded)
  ENCRYPTION_KEY: ""  # To be populated by external secret operator
  JWT_SECRET: ""      # To be populated by external secret operator
  
  # Monitoring & Observability (base64 encoded)
  JAEGER_AGENT_HOST: ""  # To be populated by external secret operator
  PROMETHEUS_AUTH_TOKEN: ""  # To be populated by external secret operator
  
---
# External Secret for Vault Integration
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: manager-q-vault-secrets
  labels:
    app: manager-q
    component: external-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: manager-q-secrets
    creationPolicy: Owner
  data:
  - secretKey: VAULT_TOKEN
    remoteRef:
      key: secret/manager-q
      property: vault_token
  - secretKey: API_SECRET_KEY
    remoteRef:
      key: secret/manager-q
      property: api_secret_key
  - secretKey: IGNITE_USERNAME
    remoteRef:
      key: secret/manager-q
      property: ignite_username
  - secretKey: IGNITE_PASSWORD
    remoteRef:
      key: secret/manager-q
      property: ignite_password
  - secretKey: PULSAR_AUTH_TOKEN
    remoteRef:
      key: secret/manager-q
      property: pulsar_auth_token
  - secretKey: SERVICE_AUTH_TOKEN
    remoteRef:
      key: secret/manager-q
      property: service_auth_token
  - secretKey: VECTORSTORE_AUTH_TOKEN
    remoteRef:
      key: secret/manager-q
      property: vectorstore_auth_token
  - secretKey: KNOWLEDGEGRAPH_AUTH_TOKEN
    remoteRef:
      key: secret/manager-q
      property: knowledgegraph_auth_token
  - secretKey: QUANTUMPULSE_AUTH_TOKEN
    remoteRef:
      key: secret/manager-q
      property: quantumpulse_auth_token
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: secret/manager-q
      property: encryption_key
  - secretKey: JWT_SECRET
    remoteRef:
      key: secret/manager-q
      property: jwt_secret 