name: Agent Deployment Pipeline

on:
  push:
    branches:
      - main
    paths:
      # This pipeline triggers if any agent's source code changes
      - 'agentQ/**.py'

jobs:
  build-and-deploy-agent:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Harbor Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push agentQ image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./agentQ/Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY_URL }}/q-platform/agentq:${{ github.sha }}

      - name: Update Kubernetes manifest
        run: |
          # This script would find the correct agent deployment file and update its image tag.
          # For example, for the devops agent:
          AGENT_DEPLOYMENT_FILE="infra/kubernetes/base/agentq/devops-deployment.yaml"
          NEW_IMAGE="${{ secrets.HARBOR_REGISTRY_URL }}/q-platform/agentq:${{ github.sha }}"
          
          # Use yq or a similar tool to update the YAML file safely
          # yq e ".spec.template.spec.containers[0].image = \"$NEW_IMAGE\"" -i $AGENT_DEPLOYMENT_FILE
          
          # For this example, we'll use sed as a placeholder
          sed -i "s|image: .*|image: $NEW_IMAGE|g" $AGENT_DEPLOYMENT_FILE
          
          echo "Updated deployment manifest:"
          cat $AGENT_DEPLOYMENT_FILE

      - name: Commit manifest changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          git add infra/kubernetes/base/agentq/devops-deployment.yaml
          git commit -m "CI: Update devops_agent image to ${{ github.sha }}" || echo "No changes to commit"
          git push 