apiVersion: v1
kind: ConfigMap
metadata:
  name: vectorstoreq-config
  labels:
    app: vectorstoreq
    component: config
data:
  # Application Configuration
  SERVICE_NAME: "vectorstoreq"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  METRICS_PORT: "9091"
  
  # Network Configuration
  HOST: "0.0.0.0"
  PORT: "8001"
  API_PORT: "8002"
  ADMIN_PORT: "8003"
  
  # Vector Database Configuration
  VECTOR_DB_TYPE: "milvus"
  VECTOR_DIMENSION: "1536"
  INDEX_TYPE: "IVF_FLAT"
  METRIC_TYPE: "L2"
  NLIST: "16384"
  
  # Milvus Configuration
  MILVUS_HOST: "milvus-proxy"
  MILVUS_PORT: "19530"
  MILVUS_USERNAME: "root"
  MILVUS_DB_NAME: "vectorstore"
  
  # Collection Configuration
  DEFAULT_COLLECTION: "embeddings"
  COLLECTION_SHARD_NUM: "2"
  COLLECTION_REPLICA_NUM: "1"
  INDEX_BUILDING_THRESHOLD: "1024"
  
  # Embedding Configuration
  EMBEDDING_MODEL: "text-embedding-ada-002"
  EMBEDDING_DIMENSION: "1536"
  EMBEDDING_BATCH_SIZE: "100"
  EMBEDDING_TIMEOUT: "30"
  
  # Search Configuration
  SEARCH_TOP_K: "10"
  SEARCH_NPROBE: "10"
  SEARCH_TIMEOUT: "30"
  SIMILARITY_THRESHOLD: "0.7"
  
  # Pulsar Configuration
  PULSAR_SERVICE_URL: "pulsar://pulsar-broker:6650"
  PULSAR_ADMIN_URL: "http://pulsar-admin:8080"
  VECTOR_REQUESTS_TOPIC: "persistent://public/default/q.vectorstore.requests"
  VECTOR_RESPONSES_TOPIC: "persistent://public/default/q.vectorstore.responses"
  EMBEDDING_EVENTS_TOPIC: "persistent://public/default/q.vectorstore.embedding-events"
  
  # Health Check Configuration
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_PORT: "8001"
  
  # Observability
  ENABLE_TRACING: "true"
  ENABLE_METRICS: "true"
  ENABLE_PROMETHEUS: "true"
  
  # Cache Configuration
  CACHE_ENABLED: "true"
  CACHE_TYPE: "redis"
  CACHE_HOST: "redis"
  CACHE_PORT: "6379"
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "1GB"
  
  # Performance Configuration
  WORKER_PROCESSES: "4"
  WORKER_THREADS: "8"
  REQUEST_QUEUE_SIZE: "1000"
  RESPONSE_TIMEOUT: "300"
  
  # Batch Processing
  BATCH_SIZE: "1000"
  BATCH_TIMEOUT: "10"
  MAX_BATCH_SIZE: "10000"
  
  # Data Management
  DATA_RETENTION_DAYS: "30"
  CLEANUP_INTERVAL: "3600"
  VACUUM_ENABLED: "true"
  VACUUM_INTERVAL: "86400"
  
  # Security Configuration
  API_KEY_REQUIRED: "true"
  ENCRYPTION_ENABLED: "true"
  TLS_ENABLED: "true"
  
  # Backup Configuration
  BACKUP_ENABLED: "true"
  BACKUP_INTERVAL: "3600"
  BACKUP_RETENTION: "7"
  BACKUP_STORAGE: "minio"
  
  # Integration Configuration
  QUANTUMPULSE_URL: "http://quantumpulse:8000"
  KNOWLEDGEGRAPH_URL: "http://knowledgegraphq:8000"
  AGENTQ_URL: "http://agentq-default:8000"
  MANAGER_Q_URL: "http://manager-q:8003"
  
  # OpenAI Configuration
  OPENAI_API_BASE: "https://api.openai.com/v1"
  OPENAI_API_VERSION: "2023-12-01-preview"
  OPENAI_MAX_RETRIES: "3"
  OPENAI_TIMEOUT: "30"
  
  # Monitoring Configuration
  MONITORING_ENABLED: "true"
  MONITORING_INTERVAL: "30"
  ALERT_THRESHOLD_LATENCY: "1000"
  ALERT_THRESHOLD_ERROR_RATE: "0.05"
  
  # Logging Configuration
  LOG_FORMAT: "json"
  LOG_TO_PULSAR: "true"
  LOG_PULSAR_TOPIC: "persistent://public/default/vectorstore-logs"
  
  # Environment
  ENVIRONMENT: "production"
  
  # Semantic Search Configuration
  SEMANTIC_SEARCH_ENABLED: "true"
  HYBRID_SEARCH_ENABLED: "true"
  RERANKING_ENABLED: "true"
  RERANKING_MODEL: "cross-encoder"
  
  # Chunking Configuration
  CHUNK_SIZE: "1000"
  CHUNK_OVERLAP: "200"
  CHUNKING_STRATEGY: "recursive"
  
  # Metadata Configuration
  METADATA_INDEXING: "true"
  METADATA_FILTERING: "true"
  FULL_TEXT_SEARCH: "true"
  
  # Scaling Configuration
  AUTO_SCALING_ENABLED: "true"
  SCALING_METRIC: "cpu"
  SCALING_THRESHOLD: "70"
  
  # Connection Pool Configuration
  CONNECTION_POOL_SIZE: "20"
  CONNECTION_POOL_MAX_SIZE: "100"
  CONNECTION_TIMEOUT: "30"
  
  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS: "1000"
  RATE_LIMIT_WINDOW: "60"
  
  # Document Processing
  DOCUMENT_PROCESSING_ENABLED: "true"
  SUPPORTED_FORMATS: "pdf,docx,txt,md,json,csv"
  MAX_DOCUMENT_SIZE: "100MB"
  
  # Vector Operations
  VECTOR_OPERATIONS_ENABLED: "true"
  VECTOR_ARITHMETIC_ENABLED: "true"
  VECTOR_SIMILARITY_FUNCTIONS: "cosine,dot_product,euclidean"
  
  # Experimental Features
  EXPERIMENTAL_FEATURES_ENABLED: "false"
  BETA_FEATURES_ENABLED: "false" 