# ManagerQ Service Configuration
service:
  name: manager-q
  version: "1.0.0"
  port: 8003
  host: "0.0.0.0"
  
  # Health check configuration
  health_check:
    enabled: true
    path: "/health"
    interval: 30
    timeout: 5

# Database configuration
database:
  type: "postgresql"
  host: "postgres"
  port: 5432
  name: "managerq"
  username: "managerq"
  # Password will be read from Vault
  ssl_mode: "require"
  max_connections: 20
  pool_size: 10

# Cache configuration
cache:
  type: "redis"
  host: "redis"
  port: 6379
  db: 0
  ttl: 3600

# Message broker configuration
pulsar:
  service_url: "pulsar://pulsar-broker:6650"
  admin_url: "http://pulsar-admin:8080"
  topics:
    agent_registrations: "persistent://public/default/q.agentq.registrations"
    agent_results: "persistent://public/default/q.agentq.results"
    workflow_events: "persistent://public/default/q.workflows.events"
    task_events: "persistent://public/default/q.tasks.events"

# Workflow configuration
workflow:
  max_concurrent_workflows: 100
  max_concurrent_tasks: 500
  workflow_timeout_hours: 24
  task_timeout_minutes: 60
  retry_attempts: 3
  retry_delay: 5

# Circuit breaker configuration
circuit_breaker:
  failure_threshold: 5
  recovery_timeout: 60
  half_open_max_calls: 10

# Observability configuration
observability:
  metrics:
    enabled: true
    port: 9091
    path: "/metrics"
  tracing:
    enabled: true
    jaeger_endpoint: "http://jaeger-collector:14268"
  logging:
    level: "INFO"
    format: "json"
    output: "stdout"

# Security configuration
security:
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
    burst_size: 100

# Service discovery
services:
  agentq:
    url: "http://agentq:8000"
    timeout: 30
  h2m:
    url: "http://h2m-service:8002"
    timeout: 30
  quantumpulse:
    url: "http://quantumpulse-api:8000"
    timeout: 60
  vectorstore:
    url: "http://vectorstore-q:8001"
    timeout: 30
  knowledgegraph:
    url: "http://knowledgegraphq:8000"
    timeout: 30
  integrationhub:
    url: "http://integrationhub:8000"
    timeout: 30

# Agent management
agents:
  personalities:
    - name: "default"
      max_instances: 5
      min_instances: 2
      resources:
        cpu: "500m"
        memory: "512Mi"
    - name: "devops"
      max_instances: 3
      min_instances: 1
      resources:
        cpu: "1000m"
        memory: "1Gi"
    - name: "data-analyst"
      max_instances: 2
      min_instances: 1
      resources:
        cpu: "2000m"
        memory: "2Gi"

# Kubernetes configuration
kubernetes:
  namespace: "q-platform"
  service_account: "manager-q"
  labels:
    app: "manager-q"
    version: "1.0.0"
    component: "control-plane" 