apiVersion: v1
kind: ConfigMap
metadata:
  name: webappq-config
  labels:
    app: webappq
    component: config
data:
  # Application Configuration
  SERVICE_NAME: "webappq"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  
  # Network Configuration
  PORT: "3000"
  HOST: "0.0.0.0"
  
  # API Configuration
  REACT_APP_API_URL: "http://manager-q:8003"
  REACT_APP_AGENT_Q_URL: "http://agentq-default:8000"
  REACT_APP_H2M_URL: "http://h2m:8008"
  REACT_APP_VECTORSTORE_URL: "http://vectorstore-q:8001"
  REACT_APP_KNOWLEDGEGRAPH_URL: "http://knowledgegraphq:8000"
  REACT_APP_QUANTUMPULSE_URL: "http://quantumpulse:8000"
  REACT_APP_INTEGRATIONHUB_URL: "http://integrationhub:8006"
  REACT_APP_USERPROFILE_URL: "http://userprofileq:8005"
  
  # WebSocket Configuration
  REACT_APP_WS_URL: "ws://h2m:8009"
  REACT_APP_WS_RECONNECT_INTERVAL: "5000"
  REACT_APP_WS_MAX_RETRIES: "10"
  
  # Authentication Configuration
  REACT_APP_AUTH_ENABLED: "true"
  REACT_APP_JWT_STORAGE: "sessionStorage"
  REACT_APP_TOKEN_REFRESH: "true"
  REACT_APP_SESSION_TIMEOUT: "1800000"
  
  # Application Features
  REACT_APP_FEATURE_WORKFLOWS: "true"
  REACT_APP_FEATURE_AGENTS: "true"
  REACT_APP_FEATURE_KNOWLEDGE_GRAPH: "true"
  REACT_APP_FEATURE_VECTOR_SEARCH: "true"
  REACT_APP_FEATURE_INTEGRATIONS: "true"
  REACT_APP_FEATURE_ANALYTICS: "true"
  REACT_APP_FEATURE_CHAT: "true"
  REACT_APP_FEATURE_ADMIN: "true"
  
  # UI Configuration
  REACT_APP_THEME: "dark"
  REACT_APP_PRIMARY_COLOR: "#0066cc"
  REACT_APP_SECONDARY_COLOR: "#ff6600"
  REACT_APP_LOGO_URL: "/assets/logo.png"
  REACT_APP_FAVICON_URL: "/assets/favicon.ico"
  
  # Pagination Configuration
  REACT_APP_DEFAULT_PAGE_SIZE: "20"
  REACT_APP_MAX_PAGE_SIZE: "100"
  
  # File Upload Configuration
  REACT_APP_UPLOAD_ENABLED: "true"
  REACT_APP_MAX_FILE_SIZE: "100MB"
  REACT_APP_ALLOWED_FILE_TYPES: "pdf,doc,docx,txt,csv,xlsx,json,xml,png,jpg,jpeg,gif"
  
  # Real-time Features
  REACT_APP_NOTIFICATIONS_ENABLED: "true"
  REACT_APP_LIVE_UPDATES: "true"
  REACT_APP_TYPING_INDICATORS: "true"
  REACT_APP_PRESENCE_INDICATORS: "true"
  
  # Performance Configuration
  REACT_APP_LAZY_LOADING: "true"
  REACT_APP_VIRTUAL_SCROLLING: "true"
  REACT_APP_MEMOIZATION: "true"
  REACT_APP_CODE_SPLITTING: "true"
  
  # Monitoring & Analytics
  REACT_APP_ANALYTICS_ENABLED: "true"
  REACT_APP_ERROR_TRACKING: "true"
  REACT_APP_PERFORMANCE_MONITORING: "true"
  REACT_APP_USER_TRACKING: "true"
  
  # Internationalization
  REACT_APP_I18N_ENABLED: "true"
  REACT_APP_DEFAULT_LANGUAGE: "en"
  REACT_APP_SUPPORTED_LANGUAGES: "en,es,fr,de,zh,ja,ko"
  REACT_APP_RTL_SUPPORT: "true"
  
  # Accessibility
  REACT_APP_A11Y_ENABLED: "true"
  REACT_APP_KEYBOARD_NAVIGATION: "true"
  REACT_APP_SCREEN_READER_SUPPORT: "true"
  REACT_APP_HIGH_CONTRAST_MODE: "true"
  
  # Security Configuration
  REACT_APP_CSP_ENABLED: "true"
  REACT_APP_XSS_PROTECTION: "true"
  REACT_APP_CORS_ENABLED: "true"
  
  # Development Configuration
  REACT_APP_DEBUG_MODE: "false"
  REACT_APP_DEV_TOOLS: "false"
  REACT_APP_HOT_RELOAD: "false"
  
  # Build Configuration
  NODE_ENV: "production"
  GENERATE_SOURCEMAP: "false"
  REACT_APP_BUILD_VERSION: "1.0.0"
  REACT_APP_BUILD_DATE: "2024-01-01T00:00:00Z"
  
  # Cache Configuration
  REACT_APP_CACHE_ENABLED: "true"
  REACT_APP_CACHE_TTL: "300000"
  REACT_APP_SERVICE_WORKER: "true"
  
  # Progressive Web App
  REACT_APP_PWA_ENABLED: "true"
  REACT_APP_OFFLINE_SUPPORT: "true"
  REACT_APP_PUSH_NOTIFICATIONS: "true"
  
  # Graph Visualization
  REACT_APP_GRAPH_RENDERER: "d3"
  REACT_APP_GRAPH_PHYSICS: "true"
  REACT_APP_GRAPH_CLUSTERING: "true"
  REACT_APP_MAX_GRAPH_NODES: "1000"
  
  # Workflow Visualization
  REACT_APP_WORKFLOW_EDITOR: "true"
  REACT_APP_WORKFLOW_VALIDATION: "true"
  REACT_APP_WORKFLOW_SIMULATION: "true"
  
  # Chat Configuration
  REACT_APP_CHAT_HISTORY_LIMIT: "100"
  REACT_APP_CHAT_MESSAGE_MAX_LENGTH: "2000"
  REACT_APP_CHAT_FILE_SHARING: "true"
  REACT_APP_CHAT_MARKDOWN_SUPPORT: "true"
  
  # Dashboard Configuration
  REACT_APP_DASHBOARD_WIDGETS: "true"
  REACT_APP_DASHBOARD_CUSTOMIZATION: "true"
  REACT_APP_DASHBOARD_EXPORT: "true"
  REACT_APP_DASHBOARD_REFRESH_INTERVAL: "30000"
  
  # Table Configuration
  REACT_APP_TABLE_SORTING: "true"
  REACT_APP_TABLE_FILTERING: "true"
  REACT_APP_TABLE_EXPORT: "true"
  REACT_APP_TABLE_COLUMN_RESIZE: "true"
  
  # Form Configuration
  REACT_APP_FORM_VALIDATION: "true"
  REACT_APP_FORM_AUTO_SAVE: "true"
  REACT_APP_FORM_CONFIRMATION: "true"
  
  # Search Configuration
  REACT_APP_SEARCH_ENABLED: "true"
  REACT_APP_SEARCH_AUTOCOMPLETE: "true"
  REACT_APP_SEARCH_HISTORY: "true"
  REACT_APP_SEARCH_SUGGESTIONS: "true"
  
  # Logging Configuration
  REACT_APP_CLIENT_LOGGING: "true"
  REACT_APP_LOG_LEVEL: "warn"
  REACT_APP_LOG_TO_SERVER: "true"
  
  # Environment
  REACT_APP_ENVIRONMENT: "production"
  REACT_APP_CLUSTER_NAME: "q-platform"
  
  # External Services
  REACT_APP_GOOGLE_ANALYTICS_ID: ""
  REACT_APP_SENTRY_DSN: ""
  REACT_APP_MIXPANEL_TOKEN: ""
  
  # Feature Flags
  REACT_APP_FEATURE_FLAGS_ENABLED: "true"
  REACT_APP_BETA_FEATURES: "false"
  REACT_APP_EXPERIMENTAL_FEATURES: "false"
  
  # Mobile Configuration
  REACT_APP_MOBILE_RESPONSIVE: "true"
  REACT_APP_TOUCH_GESTURES: "true"
  REACT_APP_MOBILE_MENU: "true"
  
  # Print Configuration
  REACT_APP_PRINT_SUPPORT: "true"
  REACT_APP_PRINT_STYLES: "true"
  
  # Integration Settings
  REACT_APP_THIRD_PARTY_INTEGRATIONS: "true"
  REACT_APP_WEBHOOK_SUPPORT: "true"
  REACT_APP_API_RATE_LIMITING: "true" 