apiVersion: v1
kind: ServiceAccount
metadata:
  name: webappq
  labels:
    app: webappq
    component: rbac
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webappq
  labels:
    app: webappq
    component: rbac
rules:
# Basic pod and service discovery
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create"]
# Metrics access
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webappq
  labels:
    app: webappq
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webappq
subjects:
- kind: ServiceAccount
  name: webappq
  namespace: q-platform 